services:
  server:
    image: ghcr.io/gopher93185789/server:latest
    volumes:
      - certs:/app/certs:ro
      - docs:/app/docs:ro
    environment:
      - PORT=${PORT}
      - DSN=${DSN}

      # TLS certificate paths
      - TLS_CERT_FILE_PATH=${TLS_CERT_FILE_PATH}
      - TLS_KEY_FILE_PATH=${TLS_KEY_FILE_PATH}

      # GitHub OAuth
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GITHUB_REDIRECT_URL=${GITHUB_REDIRECT_URL}

      # Google OAuth
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URL=${GOOGLE_REDIRECT_URL}

      # Security keys
      - TOKEN_ENCRYPTION_KEY=${TOKEN_ENCRYPTION_KEY}
      - TOKEN_SIGNING_KEY=${TOKEN_SIGNING_KEY}
    ports:
      - "443:443"
    restart: on-failure:10
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "2"

volumes:
  certs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./certificates/server
  docs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./server/docs
