info:
  contact: {}
paths:
  /ping:
    get:
      consumes:
      - '*/*'
      description: Endpoint to check if the server is running
      produces:
      - text/plain
      responses:
        "200":
          description: pong
          schema:
            type: string
      summary: Healthcheck
      tags:
      - base
swagger: "2.0"
